#!/usr/bin/env bash

clear

set -eo pipefail

if [ ! -f "index.php" ]; then
  echo 'Please run this script from "drupal8" directory.'
  exit 1;
fi

#$(echo $(pwd)"/scripts/project-branch");

GULP="aexchecker/gulp"

if [ -z $(docker images -q "${GULP}") ]; then
  echo "Image '${GULP}' does not exists, creating"
  docker build -t "${GULP}" ../ci/dockerfiles/gulp
fi

GRC_AT="$(pwd)/themes/grc_at";

if [ -f "${GRC_AT}/node_modules" ]; then
  sudo rm -fr "${GRC_AT}/node_modules";
fi
if [ -f "${GRC_AT}/libraries" ]; then
  sudo rm -fr "${GRC_AT}/libraries";
fi
if [ -f "${GRC_AT}/bower_components" ]; then
  sudo rm -fr "${GRC_AT}/bower_components";
fi

echo 'Updating components ...'
docker run -it --rm -v $GRC_AT:/app $GULP ./run.sh
