#!/usr/bin/env bash

clear

set -eo pipefail

if [ ! -f "index.php" ]; then
  echo 'Please run this script from "drupal8" directory.'
  exit 1;
fi

#$(echo $(pwd)"/scripts/project-branch");

# ##############################################################################
echo "Update repo"
git pull origin master

# ##############################################################################
echo "Clean compiled files"
sudo rm -fr ./sites/default/files/php
sudo rm -fr ./sites/default/files/js
sudo rm -fr ./sites/default/files/cs
sudo rm -fr ./sites/default/files/languages
sudo chmod -R -x+X ./sites/default/files

# ##############################################################################
echo "Clear cache tables"
CACHE_TABLES=($(echo "$(drush sqlq "SHOW TABLES LIKE 'cache\_%';")" ))
TRUNCATE_CACHE_TABLES=$(printf "TRUNCATE %s; " "${CACHE_TABLES[@]}")
drush sqlq "$TRUNCATE_CACHE_TABLES" > /dev/null 2>&1

# ##############################################################################
echo "Update Drupal"
echo "$(date +"%Y%m%d%H%M%S")1" > ./sites/default/hash_salt.txt
drush rebuild
drush sqlq "$TRUNCATE_CACHE_TABLES" > /dev/null 2>&1
drush cim -y
drush updb -y
echo "$(date +"%Y%m%d%H%M%S")2" > ./sites/default/hash_salt.txt
drush sqlq "$TRUNCATE_CACHE_TABLES" > /dev/null 2>&1
drush rebuild
