<?php

/**
 * @file
 * Main code for CKEditor CodeMirror module.
 */

/**
 * Implements hook_libraries_info().
 */
function ckeditor_codemirror_libraries_info() {
  $libraries['ckeditor.codemirror'] = array(
    'name' => 'CKEditor CodeMirror plugin',
    'vendor url' => 'https://w8tcha.github.io/CKEditor-CodeMirror-Plugin',
    'download url' => 'https://github.com/w8tcha/CKEditor-CodeMirror-Plugin/releases',
    'version arguments' => array(
      'file' => 'plugin.js',
      'pattern' => '@version:\s*\'?([0-9a-zA-Z\.-]+)\'?@',
    ),
    'files' => array(
      'js' => array(
        'plugin.js',
        'js/codemirror.min.js',
      ),
      'css' => array(
        'css/codemirror.min.css',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'js/codemirror.min.js',
          ),
          'css' => array(
            'css/codemirror.min.css',
          ),
        ),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'js/codemirror.js',
          ),
          'css' => array(
            'css/codemirror.css',
            'css/codemirror.ckeditor.css',
          ),
        ),
      ),
    ),
  );

  return $libraries;
}
